# ==========================================
# COMMON CONFIGURATION FOR ALL SERVICES
# ==========================================

message=Config Server Working Successfully

# ==========================================
# COMMON JWT CONFIGURATION
# ==========================================
jwt.secret=YourSecretKeyYourSecretKeyYourSecretKeyYourSecretKeyYourSecretKey
jwt.expiration=86400000

# ==========================================
# COMMON REDIS CONFIGURATION
# ==========================================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ==========================================
# COMMON ACTUATOR CONFIGURATION
# ==========================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# ==========================================
# COMMON CONSUL DISCOVERY CONFIG
# ==========================================
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.deregister=true
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}
