server.port=8081

test.message=PROD ENVIRONMENT

spring.datasource.url=jdbc:postgresql://localhost:5434/bankdb
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.root=ERROR
