server.port=8081

message=DEV ENVIRONMENT

spring.datasource.url=jdbc:postgresql://localhost:5434/bankdb
spring.datasource.username=postgres
spring.datasource.password=1234

jwt.secret=mySuperSecretKeyForJwtToken12345678901234567890
