# ==========================================
# ORDER SERVICE SPECIFIC CONFIG
# ==========================================

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Feign
spring.cloud.openfeign.circuitbreaker.enabled=true

# Redis Cache
spring.cache.type=redis
# Swagger UI fixes for API Gateway
server.forward-headers-strategy=framework
springdoc.swagger-ui.disable-swagger-default-url=true
