server.port=8082

test.message=DEV ENVIRONMENT

# Database
spring.datasource.url=jdbc:postgresql://localhost:5434/bankdb
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consul
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500

# Health Check
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.health-check-timeout=10s
spring.cloud.consul.discovery.metadata.service-name=order-service

# Logging
logging.level.root=INFO
logging.level.com.yuvraj.orderservice=DEBUG
