# COMMON CONFIG

jwt.secret=YourSecretKeyYourSecretKeyYourSecretKeyYourSecretKeyYourSecretKey

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

# Consul
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.deregister=true
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.defaults.enabled=true

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Feign
spring.cloud.openfeign.circuitbreaker.enabled=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
