server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5434/ecommerce_payment_test
spring.datasource.username=postgres
spring.datasource.password=1234

# Disable Hibernate table generation
spring.jpa.hibernate.ddl-auto=none

# Keep test logs clean
spring.jpa.show-sql=false

# Execute schema.sql automatically
spring.sql.init.mode=always

# Disable Consul
spring.cloud.consul.enabled=false
spring.cloud.consul.discovery.enabled=false

# Logging
logging.level.root=WARN
