springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

# Swagger UI fixes for API Gateway
server.forward-headers-strategy=framework
springdoc.swagger-ui.disable-swagger-default-url=true
