server.port=8084
spring.datasource.url=jdbc:postgresql://localhost:5434/ecommerce_payment_test
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.cloud.consul.enabled=false
spring.cloud.consul.discovery.enabled=false
logging.level.root=WARN
