spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.cloud.openfeign.circuitbreaker.enabled=true
logging.level.org.springframework.cloud.consul=DEBUG
logging.level.org.springframework.web=INFO
logging.level.com.yuvraj.shipmentservice=DEBUG

# Swagger UI fixes for API Gateway
server.forward-headers-strategy=framework
springdoc.swagger-ui.disable-swagger-default-url=true
