server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5434/bankdb_test
spring.datasource.username=postgres
spring.datasource.password=1234

# Disable Hibernate table generation
spring.jpa.hibernate.ddl-auto=none

# Keep test logs cleaner
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Execute schema.sql automatically
spring.sql.init.mode=always

# Disable Consul
spring.cloud.consul.enabled=false
spring.cloud.discovery.enabled=false

logging.level.root=WARN
